### ISSUE TITLE
The mixin outputs invalid background-image CSS

### ISSUE THREAD

**Issue by ha404** [joelambert/Retina-Compass-Helpers#2]
Invalid CSS:

```
background-image: image-url ...
```

Should be:

```
background-image: url ...
```

**Comment by joelambert** [comment]
Are you actually getting `image-url` appearing in your CSS output?

I can't replicate this, `image-url()` is a compass helper ([ref](http://compass-style.org/reference/compass/helpers/urls/#image-url)) that is used to make image paths easier to use.

**Comment by ha404** [comment]
I'm sorry, I totally ignored the fact that this was built for Compass, I was trying to just use it just with plain SASS (no Compass). I found a work around, thanks though!
