### ISSUE TITLE
Missing import background-size

### ISSUE THREAD

**Issue by mlunoe** [joelambert/Retina-Compass-Helpers#4]
Hi joelambert!

Thank you for these mixins!

Though, when I tried to use it I got the error:
Undefined mixin 'background-size'

I found out that it is a default compass mixin (Reference http://compass-style.org/reference/compass/css3/background_size/) and I had to include it, like so:
@import "compass/css3/background-size";

Could you please write this in the readme or add it as an dependency in your file? I'm a newbie, so I spend some time before I found this post: https://gist.github.com/emischorr/2397147 and got it to work. Thank you again!

**Comment by joelambert** [comment]
Thanks for reporting this, can you add the `@import` to the mixin file and raise a pull request?

**Comment by mlunoe** [comment]
Done :)
